ViewComponents/GreetingViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace OdeToFood.ViewComponents
{
    public class GreetingViewComponent : ViewComponent
    {
        private IGreeter _greeter;

        public GreetingViewComponent(IGreeter greeter)
        {
            _greeter = greeter;
        }
        public IViewComponentResult Invoke()
        {
            var model = _greeter.GetGreeting();
            return View("Default" , model);
        }
    }
}

ViewComponents/LoginLogoutViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace OdeToFood.ViewComponents
{
    public class LoginLogoutViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            return View();
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta name="viewport" content="width=device-width"/>
    <title>@ViewBag.Title</title>
</head>
<body>
<div class="container">
    
    @await Component.InvokeAsync("LoginLogout")
    <h2>OdeToFood</h2>

    @RenderBody()
</div>

<footer>
    @RenderSection("footer" , false)
    @await  Component.InvokeAsync("Greeting")
</footer>
</body>
</html>

Views/Shared/_Summary.cshtml
@model Restaurant
@{
    ViewData["Title"] = "_Summary";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<section>
    <h3>@Model.Name</h3>

    <div>Cuisine : @Model.Cuisine</div>
    <a asp-action="Details" asp-route-id="@Model.Id">รายละเอียด</a>
    <a asp-action="Edit" asp-route-id="@Model.Id">แก้ไข</a>
</section>